package ru.gb.course1.androidl2layoutscalculatorhw.domain.entities;

public enum InputSymbol {
    MULTIPL_OPERATION, DIVIDE_OPERATION, SUBSTRACT_OPERATION, ADD_OPERATION,
    PERFORM_CALC,
    CLEAR_ALL_OPERATION, CLEAR_LAST_SYMBOL_OPERATION,
    SQRT_OPERATION, INVERSION_OPERATION,
    ONE_DIGIT, TWO_DIGIT, THREE_DIGIT, FOUR_DIGIT, FIVE_DIGIT, SIX_DIGIT, SEVEN_DIGIT,
    EIGHT_DIGIT, NINE_DIGIT, ZERO_DIGIT,
    DEC_POINT
}
